import { User, UserRoleType } from "../interfaces";
// Omit is a standard utility type, we define it here for clarity if not available globally
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

/**
 * Utility function to get a random integer between min and max (inclusive).
 * Placed outside the class as a shared utility.
 * @param min The minimum value.
 * @param max The maximum value.
 * @returns A random integer.
 */
const getRandomInt = (min: number, max: number): number => {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

// --- CONSTANTS ---
const EMAIL_DOMAINS = ["testmail.com", "example.org", "qa-demo.net", "fake.co"];
// Characters allowed for random name generation (letters, numbers, and underscore)
const NAME_CHARS = "abcdefghijklmnopqrstuvwxyz0123456789_";
const NUMBERS = "0123456789";

/**
 * A lightweight utility class mimicking core functionalities of a library like Lodash,
 * primarily focused on generating random data for testing purposes.
 */
class TestDataGenerator {
  /**
   * Generates a random string of a specified length using the defined character set.
   * @param length The desired length of the random string.
   * @param chars The set of characters to use for generation.
   * @returns A random string.
   */
  public generateRandomString(length: number, chars: string): string {
    let result = "";
    for (let i = 0; i < length; i++) {
      result += chars.charAt(getRandomInt(0, chars.length - 1));
    }
    return result;
  }

  /**
   * Generates a random 10-digit phone number in a common format: (XXX) XXX-XXXX.
   * @returns A string representing a random phone number.
   */
  public getRandomPhoneNumber(): string {
    const areaCode = getRandomInt(200, 999).toString();
    const prefix = getRandomInt(100, 999).toString();
    const lineNumber = getRandomInt(1000, 9999).toString();
    return `(${areaCode}) ${prefix}-${lineNumber}`;
  }

  /**
   * Generates a random string suitable for a first name (6-12 characters).
   * @returns A random name string.
   */
  public getRandomFirstName(): string {
    const length = getRandomInt(6, 12);
    const randomString = this.generateRandomString(length, NAME_CHARS);
    // Capitalize the first letter for readability
    return randomString.charAt(0).toUpperCase() + randomString.slice(1);
  }

  /**
   * Generates a random string suitable for a last name (6-12 characters).
   * @returns A random name string.
   */
  public getRandomLastName(): string {
    const length = getRandomInt(6, 12);
    const randomString = this.generateRandomString(length, NAME_CHARS);
    // Capitalize the first letter for readability
    return randomString.charAt(0).toUpperCase() + randomString.slice(1);
  }

  /**
   * Generates a random 5-digit postal code (suitable for many regions).
   * @returns A number representing a random postal code.
   */
  public getRandomPostalCode(): string {
    // Generate a random 5-digit number (10000 to 99999)
    return getRandomInt(10000, 99999).toString();
  }

  /**
   * Generates a random email address using the provided username and a random domain.
   * @param userName The prefix to be used for the email address.
   * @returns A string representing a random email address.
   */
  public getRandomEmail(userName: string): string {
    const domain = EMAIL_DOMAINS[getRandomInt(0, EMAIL_DOMAINS.length - 1)];
    return `${userName}@${domain}`;
  }

  /**
   * Generates a full random user object ready for insertion into the database.
   * The returned object omits the _id field, as it is generated by MongoDB.
   * @param userRole The specific role to assign to the generated user.
   * @returns An object of type Omit<User, '_id'>.
   */
  public getRandomUser(userRole: UserRoleType): Omit<User, "_id"> {
    const firstName = this.getRandomFirstName();
    const lastName = this.getRandomLastName();
    // Generate a unique username by combining parts of the name and a random number string
    const username = `${firstName.toLowerCase()}.${lastName.toLowerCase()}_${this.generateRandomString(4, NUMBERS)}`;

    // Note: The phone field is included here based on your last code snippet,
    // assuming it is either optional in the User interface or you intended to add it.
    const newUser: Omit<User, "_id"> = {
      username: username,
      role: userRole,
      firstName: firstName,
      lastName: lastName,
      postalCode: this.getRandomPostalCode(),
      isDeleted: false,
      isVisible: true,
      email: this.getRandomEmail(username),
      phone: this.getRandomPhoneNumber(),
    };
    return newUser;
  }
}

export const _ = new TestDataGenerator();
